SHOW SERVICES IN SCHEMA SUPPLY_CHAIN_DB.INVOICING
--SHOW SERVICES IN SCHEMA <your_schema>;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET ENABLE_CORTEX_ANALYST = TRUE;

SELECT SYSTEM$IS_FEATURE_ENABLED('CORTEX_ANALYST');

SELECT CURRENT_VERSION();
SELECT CURRENT_REGION();
SHOW FUNCTIONS LIKE '%COMPLETE%' IN DATABASE SNOWFLAKE;

10.19.101
AWS_US_WEST_2
AI_COMPLETE
AI_COMPLETE
AI_COMPLETE
AI_COMPLETE
AI_COMPLETE
COMPLETE
COMPLETE
COMPLETE
COMPLETE
COMPLETE
COMPLETE
TRY_COMPLETE
TRY_COMPLETE


SELECT 'https://app.snowflake.com/' || CURRENT_ORGANIZATION_NAME() || '/' || CURRENT_ACCOUNT_NAME() || '/#/studio/analyst/databases/SAMPLE_DATA/schemas/TPCDS_SF10TCL/semanticView/TPCDS_SEMANTIC_VIEW_SM/edit' AS RESULT;

SELECT *
FROM SNOWFLAKE.ORGANIZATION_USAGE.REMAINING_BALANCE_DAILY
ORDER BY DATE DESC
LIMIT 1;

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_ADMIN;
GRANT ROLE OPENFLOW_ADMIN TO USER puneet222;

GRANT CREATE OPENFLOW DATA PLANE INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE OPENFLOW RUNTIME INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

ALTER USER puneet222 SET DEFAULT_ROLE = OPENFLOW_ADMIN;
ALTER USER puneet222 SET DEFAULT_SECONDARY_ROLES = ('ALL');


USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS PG_CDC_POC;

CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS OPENFLOW_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PG_CDC_POC TO ROLE OPENFLOW_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE OPENFLOW_WH TO ROLE OPENFLOW_ROLE;

CREATE USER IF NOT EXISTS OPENFLOW_USER TYPE = SERVICE
  COMMENT = 'Service identity for Openflow Postgres CDC connector';
GRANT ROLE OPENFLOW_ROLE TO USER OPENFLOW_USER;
GRANT ROLE OPENFLOW_ROLE TO ROLE OPENFLOW_ADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS poc_limit
  WITH CREDIT_QUOTA = 100   -- adjust based on your actual $/credit rate
    FREQUENCY = NEVER
    TRIGGERS
      ON 75 PERCENT DO NOTIFY
      ON 90 PERCENT DO SUSPEND
      ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE OPENFLOW_WH SET RESOURCE_MONITOR = poc_limit;
ALTER ACCOUNT SET RESOURCE_MONITOR = poc_limit;

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE postgres TO ROLE OPENFLOW_ROLE;

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE postgres TO ROLE OPENFLOW_ROLE;
GRANT USAGE ON SCHEMA postgres.public TO ROLE OPENFLOW_ROLE;
GRANT SELECT ON TABLE postgres.public.customer_new TO ROLE OPENFLOW_ROLE;

SHOW DATABASES LIKE 'postgres';


SELECT 
    date,
    free_usage_balance,
    capacity_balance,
    on_demand_consumption_balance,
    rollover_balance,
    currency
FROM SNOWFLAKE.ORGANIZATION_USAGE.REMAINING_BALANCE_DAILY
ORDER BY date DESC
LIMIT 1;

show network policies

describe network policy POSTGRES_INGRESS_POLICY_POSTGRES

SELECT CURRENT_ACCOUNT(), CREATED_ON
FROM SNOWFLAKE.ORGANIZATION_USAGE.ACCOUNTS;

USE ROLE ACCOUNTADMIN;
USE DATABASE PG_CDC_POC;

CREATE NETWORK RULE IF NOT EXISTS OPENFLOW_PG_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('2wom4h7vsra7pcejpsmasm244m.eqmrbrh-czb01896.us-west-2.aws.postgres.snowflake.app:5432');

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS OPENFLOW_PG_EAI
  ALLOWED_NETWORK_RULES = (OPENFLOW_PG_NETWORK_RULE)
  ENABLED = TRUE;

  GRANT USAGE ON INTEGRATION OPENFLOW_PG_EAI TO ROLE OPENFLOW_ROLE;


  USE ROLE OPENFLOW_ROLE;
USE WAREHOUSE OPENFLOW_WH;
SHOW tables IN DATABASE PG_CDC_POC;
SHOW TABLES IN SCHEMA public;
SELECT * FROM PG_CDC_POC.PUBLIC.customer_new;

SELECT * FROM PG_CDC_POC.public.customer_new LIMIT 10;

describe table PG_CDC_POC.public.customer_new;

USE ROLE ACCOUNTADMIN;
DROP TABLE IF EXISTS PG_CDC_POC.public.customer_new;

SHOW TABLES IN DATABASE PG_CDC_POC;

SELECT COUNT(*) FROM PG_CDC_POC.public.customer_new;

USE ROLE OPENFLOW_ADMIN;
SHOW COMPUTE POOLS;


USE ROLE ACCOUNTADMIN;
SHOW RESOURCE MONITORS;

ALTER RESOURCE MONITOR poc_limit SET CREDIT_QUOTA = 200;

DESCRIBE EXTERNAL ACCESS INTEGRATION OPENFLOW_PG_EAI;

DESCRIBE NETWORK RULE OPENFLOW_PG_NETWORK_RULE;

USE ROLE ACCOUNTADMIN;
SHOW POSTGRES INSTANCES;

--------------------------------

USE ROLE ACCOUNTADMIN;
USE DATABASE PG_CDC_POC;  -- or wherever you want this rule stored

CREATE NETWORK RULE PG_OPENFLOW_INGRESS_RULE
  TYPE = IPV4
  MODE = POSTGRES_INGRESS
  VALUE_LIST = ('0.0.0.0/0');  -- ⚠️ for POC only, see note below

CREATE NETWORK POLICY PG_OPENFLOW_NETWORK_POLICY
  ALLOWED_NETWORK_RULE_LIST = ('PG_OPENFLOW_INGRESS_RULE');

SHOW POSTGRES INSTANCES;

ALTER POSTGRES INSTANCE "postgres" SET NETWORK_POLICY = 'PG_OPENFLOW_NETWORK_POLICY';


USE ROLE ACCOUNTADMIN;
ALTER USER OPENFLOW_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9wzUAJa1OwqhCDkaLSmU2xBxQwHj40z2EGHTPiWuhGCOnjDMObCIxQTJu0pQIDAQAB';

DESC USER OPENFLOW_USER;

USE ROLE OPENFLOW_ROLE;
DROP TABLE IF EXISTS PG_CDC_POC.public.customer_new;


SELECT
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 2) AS TOTAL_CREDITS,
    ROUND(SUM(CREDITS_USED_COMPUTE), 2) AS COMPUTE_CREDITS,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 2) AS CLOUD_SERVICE_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(HOUR, -10, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC;



SELECT
    SERVICE_TYPE,
    SUM(CREDITS_USED) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE START_TIME >= DATEADD(day,-7,CURRENT_TIMESTAMP())
GROUP BY SERVICE_TYPE
ORDER BY CREDITS DESC;

use role openflow_role;
select * from PG_CDC_POC."public"."customer_new_26" order by 4 desc;


GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA PG_CDC_POC.PUBLIC
TO ROLE OPENFLOW_ROLE;

SHOW TABLES IN SCHEMA PG_CDC_POC."public";


USE DATABASE PG_CDC_POC;

SHOW SCHEMAS;

SELECT * FROM pg_publication;
